#!/usr/bin/env python3
import argparse
import importlib
import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from pptx import Presentation

from lib import design as d
from lib import shapes
from lib import roundtrip_state
from lib import comments as comments_lib


BASE = Path(__file__).parent
shapes.set_assets_dir(BASE / "assets")

parser = argparse.ArgumentParser(description="Build the generated slide deck.")
parser.parse_args()  # no options; supports --help and rejects stray arguments

# Load the bundled base deck (lib/base.pptx: masters/layouts/theme, no slides,
# captured by scaffold.py). It is read-only; the built deck is written to
# out/<project-name>.pptx. build_deck.py is self-contained and needs no source
# .pptx. To refresh layouts/theme after editing them in PowerPoint, run
# recapture_base.py, which rewrites lib/base.pptx.
base_deck = BASE / "lib" / "base.pptx"
if not base_deck.exists():
    sys.exit(
        f"Base deck not found: {base_deck}\n"
        "Re-run scaffold.py to regenerate it, or refresh it with recapture_base.py."
    )
prs = Presentation(str(base_deck))
prs.slide_width = d.SLIDE_W
prs.slide_height = d.SLIDE_H

# Remove layout-level footer / slide-number chrome. The generator emits those
# shapes as normal slide shapes so they are selectable; leaving them on the
# layout would create duplicate locked background copies.
shapes.remove_layout_chrome(prs)

# Defensive: strip any content slides from the base deck. The bundled
# lib/base.pptx has none; this only guards against a hand-edited base. The
# generated slides below are what populate the deck.
original_slides = list(prs.slides)
for old_slide in original_slides:
    slide_id = old_slide.slide_id
    rId = None
    for rel in prs.part.rels.values():
        if rel.target_part == old_slide.part:
            rId = rel.rId
            break
    if rId:
        prs.part.drop_rel(rId)
    for sldId in list(prs.slides._sldIdLst):
        if sldId.id == slide_id:
            prs.slides._sldIdLst.remove(sldId)
            break

slide_files = sorted(
    (BASE / "slides").glob("s*.py"),
    key=lambda p: int(p.stem.split("_", 1)[0][1:]) if p.stem[1:].split("_", 1)[0].isdigit() else p.stem,
)
# Flatten layouts across ALL slide masters so LAYOUT indices generated by
# generate_slides.py (which spans every master) resolve to the correct layout.
# Using only prs.slide_layouts (first master) would misresolve slides bound to
# any other master.
all_layouts = [layout for master in prs.slide_masters for layout in master.slide_layouts]

for i, path in enumerate(slide_files, start=1):
    mod = importlib.import_module(f"slides.{path.stem}")
    # Use the deck's sequential slide number so deletions don't create gaps.
    slide_num = i
    layout_idx = getattr(mod, "LAYOUT", 6)
    if layout_idx >= len(all_layouts):
        layout_idx = 0
    slide = prs.slides.add_slide(all_layouts[layout_idx])
    # Remove layout placeholders so the generated slide code draws everything as normal shapes.
    # Placeholders are rendered as text boxes / boxes by the generator, not inherited from the layout.
    for shape in list(slide.shapes):
        if shape.is_placeholder:
            sp = shape.element
            sp.getparent().remove(sp)
    mod.add_slide(prs, slide, slide_num)
    shapes.renumber_slide_ids(slide)

shapes.reorder_presentation(prs)

out = BASE / "out"
out.mkdir(exist_ok=True)
output_name = f"{BASE.name}.pptx"
output_path = out / output_name
prs.save(output_path)
shapes.postprocess_svg_fallbacks(output_path)
# Re-attach any PowerPoint comments preserved by scaffold.py (no-op when the
# project has no comments/). Runs before the native pass so the injected parts
# get the same declaration/zip-order normalization as the rest of the package.
n_comments = comments_lib.inject_comments(output_path, BASE / "comments")
shapes.postprocess_powerpoint_native(output_path)
print(f"Wrote {output_path}")
if n_comments:
    print(f"Re-attached {n_comments} preserved comment(s)")

# Run OOXML validator. Some source decks inherit a misplaced <p:notesMasterIdLst>
# after <p:sldIdLst>; PowerPoint tolerates that order but the validator flags it.
# We treat that single inherited schema warning as acceptable so the deck opens
# in PowerPoint without a repair dialog.
result = subprocess.run(
    ["npx", "@xarsh/ooxml-validator", str(output_path)],
    capture_output=True,
    text=True,
)
try:
    validation = json.loads(result.stdout)
except json.JSONDecodeError:
    print("Validator output was not valid JSON:")
    print(result.stdout)
    print(result.stderr)
    sys.exit(1)

inherited_notes_master_warning = (
    "Sch_UnexpectedElementContentExpectingComplex",
    "notesMasterIdLst",
)
filtered_errors = [
    err
    for err in validation.get("errors", [])
    if not (
        err.get("id") == inherited_notes_master_warning[0]
        and inherited_notes_master_warning[1] in err.get("description", "")
    )
]

if filtered_errors:
    print("Validator found errors:")
    print(json.dumps({"ok": False, "errors": filtered_errors}, indent=2))
    sys.exit(1)

if validation.get("errors"):
    print("Validator passed with one inherited notesMasterIdLst order warning (ignored).")
else:
    print("Validator passed with zero errors.")

# Archive the successful build so the user can roll back. Keep the 10 most recent.
backup_dir = BASE / "backup"
backup_dir.mkdir(exist_ok=True)
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
backup_path = backup_dir / f"backup_{timestamp}.pptx"
shutil.copy2(str(output_path), str(backup_path))
print(f"Archived build to {backup_path}")

backups = sorted(backup_dir.glob("backup_*.pptx"), key=lambda p: p.name)
MAX_BACKUPS = 10
for old in backups[:-MAX_BACKUPS]:
    old.unlink()
    print(f"Removed old backup {old}")

# Record that this freshly built deck is now in sync with the code. autosync.py
# compares out/<name>.pptx against this marker to tell a human PowerPoint edit
# apart from our own build, so it never re-syncs code from a deck we built.
roundtrip_state.stamp(BASE, output_path)
print(f"Recorded round-trip sync state ({BASE / roundtrip_state.STATE_FILENAME})")
